project:
  type: website
  output-dir: "docs"

website:
  title: "Final"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: cerulean
    css: styles.css
    toc: true

editor: visual

